//
// Activity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Activity: Codable {

    public var id: Int
    public var description: String

    public init(id: Int, description: String) {
        self.id = id
        self.description = description
    }

}

