//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse200: Codable {

    public var hasNext: Bool
    public var results: [Project]

    public init(hasNext: Bool, results: [Project]) {
        self.hasNext = hasNext
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case hasNext = "has_next"
        case results
    }

}

