//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case gate = "gate"
        case project = "project"
        case region = "region"
        case product = "product"
    }
    public var type: ModelType
    public var pk: Int

    public init(type: ModelType, pk: Int) {
        self.type = type
        self.pk = pk
    }

}

