//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2001: Codable {

    public var hasNext: Bool?
    public var results: [Region]

    public init(hasNext: Bool? = nil, results: [Region]) {
        self.hasNext = hasNext
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case hasNext = "has_next"
        case results
    }

}

