//
// ManagerSimplified.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ManagerSimplified: Codable {

    public var id: Int
    public var firstName: String
    public var lastName: String
    public var email: String

    public init(id: Int, firstName: String, lastName: String, email: String) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case firstName = "first_name"
        case lastName = "last_name"
        case email
    }

}

