//
// Product.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Product: Codable {

    public var id: Int
    public var name: String
    public var manager: ManagerSimplified
    public var regionProducts: [RegionProduct]

    public init(id: Int, name: String, manager: ManagerSimplified, regionProducts: [RegionProduct]) {
        self.id = id
        self.name = name
        self.manager = manager
        self.regionProducts = regionProducts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case manager
        case regionProducts = "region_products"
    }

}

