//
// Project.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Project: Codable {

    public enum Status: String, Codable, CaseIterable {
        case red = "red"
        case green = "green"
        case yellow = "yellow"
    }
    public var id: Int
    public var name: String
    public var sapNumber: String
    public var status: Status
    public var approvedDate: Date
    public var originalProjectMonths: Int
    public var expectedProjectMonths: Int
    public var ongoingActivities: [Activity]
    public var challenges: [Challenge]
    public var manager: ManagerSimplified
    public var gates: [Gate]
    public var businessUnit: String

    public init(id: Int, name: String, sapNumber: String, status: Status, approvedDate: Date, originalProjectMonths: Int, expectedProjectMonths: Int, ongoingActivities: [Activity], challenges: [Challenge], manager: ManagerSimplified, gates: [Gate], businessUnit: String) {
        self.id = id
        self.name = name
        self.sapNumber = sapNumber
        self.status = status
        self.approvedDate = approvedDate
        self.originalProjectMonths = originalProjectMonths
        self.expectedProjectMonths = expectedProjectMonths
        self.ongoingActivities = ongoingActivities
        self.challenges = challenges
        self.manager = manager
        self.gates = gates
        self.businessUnit = businessUnit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case sapNumber = "sap_number"
        case status
        case approvedDate = "approved_date"
        case originalProjectMonths = "original_project_months"
        case expectedProjectMonths = "expected_project_months"
        case ongoingActivities = "ongoing_activities"
        case challenges
        case manager
        case gates
        case businessUnit = "business_unit"
    }

}

