//
// RegionProduct.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RegionProduct: Codable {

    public enum Status: String, Codable, CaseIterable {
        case red = "red"
        case green = "green"
        case yellow = "yellow"
    }
    public var id: Int
    public var authorizationDate: Date
    public var status: Status
    public var currentAuthorizationDate: Date
    public var monthlyData: [MonthlyData]

    public init(id: Int, authorizationDate: Date, status: Status, currentAuthorizationDate: Date, monthlyData: [MonthlyData]) {
        self.id = id
        self.authorizationDate = authorizationDate
        self.status = status
        self.currentAuthorizationDate = currentAuthorizationDate
        self.monthlyData = monthlyData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case authorizationDate = "authorization_date"
        case status
        case currentAuthorizationDate = "current_authorization_date"
        case monthlyData = "monthly_data"
    }

}

